# Generated by Django 5.2.7 on 2025-10-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electiva',
            fields=[
                ('electiva_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_electiva', models.CharField(max_length=100)),
                ('es_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('materia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('es_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('pensum_id', models.AutoField(primary_key=True, serialize=False)),
                ('anio_creacion', models.IntegerField(null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('email_usuario', models.EmailField(max_length=100, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaElectiva',
            fields=[
                ('oferta_electiva_id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.IntegerField()),
                ('es_activa', models.BooleanField(default=True)),
                ('electiva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.electiva')),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='pensum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pensum'),
        ),
        migrations.AddField(
            model_name='pensum',
            name='programa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programa'),
        ),
        migrations.AddField(
            model_name='electiva',
            name='programa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programa'),
        ),
    ]
