# Generated by Django 5.1.7 on 2025-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiva',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
