# Generated by Django 5.2.7 on 2025-11-17 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_electiva_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionElegibilidad',
            fields=[
                ('configuracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_avance_minimo', models.DecimalField(decimal_places=4, default=0.6, help_text='Porcentaje mínimo de avance requerido (0.60 = 60%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('nota_aprobatoria', models.DecimalField(decimal_places=1, default=3.0, help_text='Nota mínima para considerar una materia aprobada', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('semestre_limite_electivas', models.IntegerField(default=7, help_text='Hasta qué semestre se exige tener TODO aprobado', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_creditos_obligatorios', models.IntegerField(default=151, help_text='Total de créditos obligatorios del pensum', validators=[django.core.validators.MinValueValidator(1)])),
                ('niveles_creditos_periodos', models.JSONField(default=dict, help_text="Reglas por nivel. Ejemplo: {8: {'min_creditos': 112, 'max_periodos': 7}}")),
                ('es_activo', models.BooleanField(default=True, help_text='True si esta configuración está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('programa_id', models.ForeignKey(blank=True, help_text='Programa académico asociado. Si es None, es configuración global.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programa')),
            ],
            options={
                'verbose_name': 'Configuración de Elegibilidad',
                'verbose_name_plural': 'Configuraciones de Elegibilidad',
                'db_table': 'configuracion_elegibilidad',
                'indexes': [models.Index(fields=['programa_id', 'es_activo'], name='configuraci_program_4de979_idx'), models.Index(fields=['es_activo'], name='configuraci_es_acti_ac8123_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_activo', True)), fields=('programa_id', 'es_activo'), name='unique_active_config_per_program')],
            },
        ),
    ]
