# Generated by Django 5.2.7 on 2025-11-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configuracionelegibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionelegibilidad',
            name='total_creditos_obligatorios',
        ),
    ]
