# Generated by Django 5.2.7 on 2025-11-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_programa_id_required'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configuracionelegibilidad',
            new_name='configuraci_program_c19b4f_idx',
            old_name='configuraci_program_4de979_idx',
        ),
        migrations.AlterField(
            model_name='configuracionelegibilidad',
            name='programa_id',
            field=models.ForeignKey(db_column='programa_id', help_text='Programa académico asociado (requerido)', on_delete=django.db.models.deletion.CASCADE, to='api.programa'),
        ),
    ]
